// Generated by CoffeeScript 1.7.1
(function() {
  var assert, cube, isOdd5d;

  cube = require('../simpleFunctions').cube;

  isOdd5d = require('../simpleFunctions').isFiveDigitOddNumber;

  assert = require('assert');

  describe('testing a coffeescript cube function', function() {
    it('3 cubed is 27', function() {
      return assert.equal(27, cube(3));
    });
    return it('-3 cubed is -27', function() {
      return assert.equal(-27, cube(-3));
    });
  });

  describe('incomplete test coverage example', function() {
    it('5 is not one', function() {
      return assert.equal(false, isOdd5d(5));
    });
    return it('30525 is not one', function() {
      return assert.equal(false, isOdd5d(30524));
    });
  });

}).call(this);
