// Generated by CoffeeScript 1.7.1
(function() {
  exports.cube = function(number) {
    return number * number * number;
  };

  exports.isFiveDigitOddNumber = function(number) {
    var test;
    test = number % 2;
    if (number >= 10000) {
      if (number <= 99999) {
        if (test === 1) {
          return true;
        }
      }
    }
    return false;
  };

}).call(this);
