// Generated by CoffeeScript 1.7.1
(function() {
  exports.index = function(req, res) {
    res.locals = {
      title: 'GPA Calculator',
      description: 'Enter your grades and credits and see your GPA'

      /*'An example of one way to build a powerful web app based on Node.js' */
    };
    return res.render('index');
  };

}).call(this);

//# sourceMappingURL=index.map
