// Generated by CoffeeScript 1.7.1
(function() {
  var Schema, Section, classGrades, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  classGrades = new Schema({
    grade: String,
    credit: String
  });

  Section = mongoose.model('Section', Section);

  module.exports = {
    Section: Section
  };

}).call(this);

//# sourceMappingURL=gpaSchema.map
